import type {
  HealthConnectorAvailability,
  HealthConnectorCategory,
  HealthConnectorDefinition,
  HealthConnectorId,
} from "./types"

/** Full catalog including wearables / FHIR — use {@link getHealthConnectorCatalog} for UI (evidence-only). */
const ALL_HEALTH_CONNECTOR_DEFINITIONS: HealthConnectorDefinition[] = [
  {
    id: "pubmed",
    name: "PubMed",
    category: "evidence",
    protocol: "http_api",
    availability: "live",
    description: "Search biomedical literature from PubMed.",
    domain: "pubmed.ncbi.nlm.nih.gov",
    isFeatured: true,
    requiredCredentials: [],
  },
  {
    id: "guideline",
    name: "Guideline Search",
    category: "evidence",
    protocol: "http_api",
    availability: "live",
    description: "Search clinical guidelines and regional recommendations.",
    domain: "guidelines",
    isFeatured: true,
    requiredCredentials: [],
  },
  {
    id: "clinical_trials",
    name: "ClinicalTrials.gov",
    category: "evidence",
    protocol: "http_api",
    availability: "live",
    description: "Access ongoing and completed clinical trial records.",
    domain: "clinicaltrials.gov",
    isFeatured: true,
    requiredCredentials: [],
  },
  {
    id: "openfda",
    name: "OpenFDA",
    category: "evidence",
    protocol: "http_api",
    availability: "live",
    description: "Use FDA label and safety datasets for medication context.",
    domain: "open.fda.gov",
    isFeatured: true,
    requiredCredentials: [],
  },
  {
    id: "scholar_gateway",
    name: "Scholar Gateway",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Broader scholarly evidence retrieval and research citations.",
    domain: "scholar.google.com",
    isFeatured: false,
    requiredCredentials: [
      {
        env: "EXA_API_KEY",
        label: "Exa API Key",
        secret: true,
      },
    ],
  },
  {
    id: "biorxiv",
    name: "bioRxiv",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Preprint evidence from bioRxiv and medRxiv.",
    domain: "biorxiv.org",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "npi_registry",
    name: "NPI Registry",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "US National Provider Identifier lookup and verification.",
    domain: "npiregistry.cms.hhs.gov",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "cms_coverage",
    name: "CMS Coverage",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Coverage policy search across CMS LCD and NCD resources.",
    domain: "cms.gov",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "chembl",
    name: "ChEMBL",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Molecule and compound data from ChEMBL.",
    domain: "ebi.ac.uk",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "synapse",
    name: "Synapse",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Dataset metadata search for translational research context.",
    domain: "synapse.org",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "benchling",
    name: "Benchling",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Lab workflow and protocol context for experimental work.",
    domain: "benchling.com",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "biorender",
    name: "BioRender",
    category: "evidence",
    protocol: "http_api",
    availability: "beta",
    description: "Scientific illustration and visual reference lookup.",
    domain: "biorender.com",
    isFeatured: false,
    requiredCredentials: [],
  },
  {
    id: "fitbit",
    name: "Fitbit",
    category: "wearable",
    protocol: "oauth2",
    availability: "beta",
    description: "Sync activity, heart rate, and sleep data from Fitbit.",
    domain: "dev.fitbit.com",
    isFeatured: true,
    requiredCredentials: [
      { env: "FITBIT_CLIENT_ID", label: "Fitbit Client ID" },
      { env: "FITBIT_CLIENT_SECRET", label: "Fitbit Client Secret", secret: true },
      { env: "FITBIT_REDIRECT_URI", label: "Fitbit Redirect URI" },
    ],
    authorizationUrlEnv: "FITBIT_AUTH_URL",
    tokenUrlEnv: "FITBIT_TOKEN_URL",
  },
  {
    id: "oura",
    name: "Oura",
    category: "wearable",
    protocol: "oauth2",
    availability: "beta",
    description: "Sync readiness, sleep, and heart-rate trends from Oura.",
    domain: "developer.ouraring.com",
    isFeatured: true,
    requiredCredentials: [
      { env: "OURA_CLIENT_ID", label: "Oura Client ID" },
      { env: "OURA_CLIENT_SECRET", label: "Oura Client Secret", secret: true },
      { env: "OURA_REDIRECT_URI", label: "Oura Redirect URI" },
    ],
    authorizationUrlEnv: "OURA_AUTH_URL",
    tokenUrlEnv: "OURA_TOKEN_URL",
  },
  {
    id: "whoop",
    name: "WHOOP",
    category: "wearable",
    protocol: "oauth2",
    availability: "beta",
    description: "Sync strain, recovery, and sleep metrics from WHOOP.",
    domain: "developer.whoop.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "WHOOP_CLIENT_ID", label: "WHOOP Client ID" },
      { env: "WHOOP_CLIENT_SECRET", label: "WHOOP Client Secret", secret: true },
      { env: "WHOOP_REDIRECT_URI", label: "WHOOP Redirect URI" },
    ],
    authorizationUrlEnv: "WHOOP_AUTH_URL",
    tokenUrlEnv: "WHOOP_TOKEN_URL",
  },
  {
    id: "withings",
    name: "Withings",
    category: "wearable",
    protocol: "oauth2",
    availability: "beta",
    description: "Sync wearable and biometric signals from Withings.",
    domain: "developer.withings.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "WITHINGS_CLIENT_ID", label: "Withings Client ID" },
      {
        env: "WITHINGS_CLIENT_SECRET",
        label: "Withings Client Secret",
        secret: true,
      },
      { env: "WITHINGS_REDIRECT_URI", label: "Withings Redirect URI" },
    ],
    authorizationUrlEnv: "WITHINGS_AUTH_URL",
    tokenUrlEnv: "WITHINGS_TOKEN_URL",
  },
  {
    id: "polar",
    name: "Polar AccessLink",
    category: "wearable",
    protocol: "oauth2",
    availability: "beta",
    description: "Sync training load and heart data from Polar AccessLink.",
    domain: "polar.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "POLAR_FITNESS_CLIENT_ID", label: "Polar AccessLink Client ID" },
      { env: "POLAR_FITNESS_CLIENT_SECRET", label: "Polar AccessLink Client Secret", secret: true },
      { env: "POLAR_FITNESS_REDIRECT_URI", label: "Polar AccessLink Redirect URI" },
    ],
    authorizationUrlEnv: "POLAR_FITNESS_AUTH_URL",
    tokenUrlEnv: "POLAR_FITNESS_TOKEN_URL",
  },
  {
    id: "garmin",
    name: "Garmin Health",
    category: "wearable",
    protocol: "oauth1a",
    availability: "beta",
    description: "Sync wearable and activity signals through Garmin Health APIs.",
    domain: "developer.garmin.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "GARMIN_CONSUMER_KEY", label: "Garmin Consumer Key" },
      {
        env: "GARMIN_CONSUMER_SECRET",
        label: "Garmin Consumer Secret",
        secret: true,
      },
      { env: "GARMIN_REDIRECT_URI", label: "Garmin Redirect URI" },
    ],
    authorizationUrlEnv: "GARMIN_AUTH_URL",
    tokenUrlEnv: "GARMIN_TOKEN_URL",
  },
  {
    id: "apple_healthkit",
    name: "Apple HealthKit",
    category: "native_mobile",
    protocol: "native_sdk",
    availability: "coming_soon",
    description: "Native iOS HealthKit bridge for Apple device data.",
    domain: "developer.apple.com",
    isFeatured: true,
    comingSoonReason: "Requires native iOS app bridge and HealthKit entitlements.",
    requiredCredentials: [],
  },
  {
    id: "android_health_connect",
    name: "Android Health Connect",
    category: "native_mobile",
    protocol: "native_sdk",
    availability: "coming_soon",
    description: "Native Android Health Connect integration for device metrics.",
    domain: "developer.android.com",
    isFeatured: true,
    comingSoonReason:
      "Requires native Android integration and Health Connect permission review.",
    requiredCredentials: [],
  },
  {
    id: "samsung_health",
    name: "Samsung Health",
    category: "native_mobile",
    protocol: "native_sdk",
    availability: "coming_soon",
    description: "Native Samsung Health partner integration.",
    domain: "developer.samsung.com",
    isFeatured: false,
    comingSoonReason:
      "Requires Samsung partner registration, package signature approval, and native bridge.",
    requiredCredentials: [],
  },
  {
    id: "smart_epic",
    name: "SMART on FHIR (Epic)",
    category: "medical_records",
    protocol: "smart_on_fhir",
    availability: "beta",
    description: "Direct Epic SMART on FHIR patient record integration.",
    domain: "epic.com",
    isFeatured: true,
    requiredCredentials: [
      { env: "SMART_EPIC_CLIENT_ID", label: "Epic SMART Client ID" },
      { env: "SMART_EPIC_REDIRECT_URI", label: "Epic SMART Redirect URI" },
      { env: "SMART_EPIC_AUTH_URL", label: "Epic SMART Authorization URL" },
      { env: "SMART_EPIC_TOKEN_URL", label: "Epic SMART Token URL" },
      { env: "SMART_EPIC_FHIR_BASE_URL", label: "Epic SMART FHIR Base URL" },
    ],
    authorizationUrlEnv: "SMART_EPIC_AUTH_URL",
    tokenUrlEnv: "SMART_EPIC_TOKEN_URL",
  },
  {
    id: "smart_cerner",
    name: "SMART on FHIR (Oracle Health/Cerner)",
    category: "medical_records",
    protocol: "smart_on_fhir",
    availability: "beta",
    description: "Direct Oracle Health/Cerner SMART on FHIR integration.",
    domain: "cerner.com",
    isFeatured: true,
    requiredCredentials: [
      { env: "SMART_CERNER_CLIENT_ID", label: "Cerner SMART Client ID" },
      { env: "SMART_CERNER_REDIRECT_URI", label: "Cerner SMART Redirect URI" },
      { env: "SMART_CERNER_AUTH_URL", label: "Cerner SMART Authorization URL" },
      { env: "SMART_CERNER_TOKEN_URL", label: "Cerner SMART Token URL" },
      { env: "SMART_CERNER_FHIR_BASE_URL", label: "Cerner SMART FHIR Base URL" },
    ],
    authorizationUrlEnv: "SMART_CERNER_AUTH_URL",
    tokenUrlEnv: "SMART_CERNER_TOKEN_URL",
  },
  {
    id: "smart_athena",
    name: "SMART on FHIR (athenahealth)",
    category: "medical_records",
    protocol: "smart_on_fhir",
    availability: "beta",
    description: "Direct athenahealth SMART on FHIR integration.",
    domain: "athenahealth.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "SMART_ATHENA_CLIENT_ID", label: "athena SMART Client ID" },
      { env: "SMART_ATHENA_REDIRECT_URI", label: "athena SMART Redirect URI" },
      { env: "SMART_ATHENA_AUTH_URL", label: "athena SMART Authorization URL" },
      { env: "SMART_ATHENA_TOKEN_URL", label: "athena SMART Token URL" },
      { env: "SMART_ATHENA_FHIR_BASE_URL", label: "athena SMART FHIR Base URL" },
    ],
    authorizationUrlEnv: "SMART_ATHENA_AUTH_URL",
    tokenUrlEnv: "SMART_ATHENA_TOKEN_URL",
  },
  {
    id: "aggregator_1uphealth",
    name: "Aggregator (1upHealth)",
    category: "medical_records",
    protocol: "aggregator",
    availability: "beta",
    description: "Aggregator path for patient records through 1upHealth.",
    domain: "1up.health",
    isFeatured: true,
    requiredCredentials: [
      { env: "AGG_1UPHEALTH_CLIENT_ID", label: "1upHealth Client ID" },
      {
        env: "AGG_1UPHEALTH_CLIENT_SECRET",
        label: "1upHealth Client Secret",
        secret: true,
      },
      { env: "AGG_1UPHEALTH_REDIRECT_URI", label: "1upHealth Redirect URI" },
      { env: "AGG_1UPHEALTH_AUTH_URL", label: "1upHealth Authorization URL" },
      { env: "AGG_1UPHEALTH_TOKEN_URL", label: "1upHealth Token URL" },
      { env: "AGG_1UPHEALTH_FHIR_BASE_URL", label: "1upHealth FHIR Base URL" },
    ],
    authorizationUrlEnv: "AGG_1UPHEALTH_AUTH_URL",
    tokenUrlEnv: "AGG_1UPHEALTH_TOKEN_URL",
  },
  {
    id: "aggregator_health_gorilla",
    name: "Aggregator (Health Gorilla)",
    category: "medical_records",
    protocol: "aggregator",
    availability: "beta",
    description: "Aggregator path for records and labs through Health Gorilla.",
    domain: "healthgorilla.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "AGG_HEALTH_GORILLA_CLIENT_ID", label: "Health Gorilla Client ID" },
      {
        env: "AGG_HEALTH_GORILLA_CLIENT_SECRET",
        label: "Health Gorilla Client Secret",
        secret: true,
      },
      {
        env: "AGG_HEALTH_GORILLA_REDIRECT_URI",
        label: "Health Gorilla Redirect URI",
      },
      {
        env: "AGG_HEALTH_GORILLA_AUTH_URL",
        label: "Health Gorilla Authorization URL",
      },
      { env: "AGG_HEALTH_GORILLA_TOKEN_URL", label: "Health Gorilla Token URL" },
      {
        env: "AGG_HEALTH_GORILLA_FHIR_BASE_URL",
        label: "Health Gorilla FHIR Base URL",
      },
    ],
    authorizationUrlEnv: "AGG_HEALTH_GORILLA_AUTH_URL",
    tokenUrlEnv: "AGG_HEALTH_GORILLA_TOKEN_URL",
  },
  {
    id: "aggregator_redox",
    name: "Aggregator (Redox)",
    category: "medical_records",
    protocol: "aggregator",
    availability: "beta",
    description: "Aggregator path for medical records through Redox.",
    domain: "redoxengine.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "AGG_REDOX_CLIENT_ID", label: "Redox Client ID" },
      { env: "AGG_REDOX_PRIVATE_KEY", label: "Redox Private Key", secret: true },
      { env: "AGG_REDOX_AUTH_URL", label: "Redox Authorization URL" },
      { env: "AGG_REDOX_TOKEN_URL", label: "Redox Token URL" },
      { env: "AGG_REDOX_FHIR_BASE_URL", label: "Redox FHIR Base URL" },
    ],
    authorizationUrlEnv: "AGG_REDOX_AUTH_URL",
    tokenUrlEnv: "AGG_REDOX_TOKEN_URL",
  },
  {
    id: "aggregator_particle",
    name: "Aggregator (Particle Health)",
    category: "medical_records",
    protocol: "aggregator",
    availability: "beta",
    description: "Aggregator path for record retrieval through Particle Health.",
    domain: "particlehealth.com",
    isFeatured: false,
    requiredCredentials: [
      { env: "AGG_PARTICLE_CLIENT_ID", label: "Particle Client ID" },
      {
        env: "AGG_PARTICLE_CLIENT_SECRET",
        label: "Particle Client Secret",
        secret: true,
      },
      { env: "AGG_PARTICLE_AUTH_URL", label: "Particle Authorization URL" },
      { env: "AGG_PARTICLE_TOKEN_URL", label: "Particle Token URL" },
      { env: "AGG_PARTICLE_FHIR_BASE_URL", label: "Particle FHIR Base URL" },
    ],
    authorizationUrlEnv: "AGG_PARTICLE_AUTH_URL",
    tokenUrlEnv: "AGG_PARTICLE_TOKEN_URL",
  },
]

/** Evidence / literature connectors only (settings UI and public catalog API). */
export function getHealthConnectorCatalog(): HealthConnectorDefinition[] {
  return ALL_HEALTH_CONNECTOR_DEFINITIONS.filter((c) => c.category === "evidence")
}

export function getHealthConnectorById(
  connectorId: string
): HealthConnectorDefinition | undefined {
  return ALL_HEALTH_CONNECTOR_DEFINITIONS.find((connector) => connector.id === connectorId)
}

export function getHealthConnectorsByCategory(
  category: HealthConnectorCategory
): HealthConnectorDefinition[] {
  return ALL_HEALTH_CONNECTOR_DEFINITIONS.filter((connector) => connector.category === category)
}

export function getHealthConnectorsByAvailability(
  availability: HealthConnectorAvailability
): HealthConnectorDefinition[] {
  return ALL_HEALTH_CONNECTOR_DEFINITIONS.filter(
    (connector) => connector.availability === availability
  )
}

export function isNativeConnector(connectorId: HealthConnectorId): boolean {
  const connector = getHealthConnectorById(connectorId)
  return connector?.category === "native_mobile"
}
